services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: classicmodels
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql:ro

  app:
    build: .
    command: streamlit run streamlit_app.py --server.port 8501 --server.headless true
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/classicmodels
    ports:
      - '8501:8501'
    depends_on:
      - db
    volumes:
      - ./:/app:cached

volumes:
  db_data:
    driver: local